### ISSUE TITLE
Update for Eleventy 2.0.0 milestone

### ISSUE THREAD

**Issue by johnhunter** [gregives/eleventy-load#30]
When Eleventy 2.0.0 release is imminent we need to:

- [ ] Verify eleventy-load works with the new version
- [ ] Fix and add test mocks if 11ty plugin interface has changed
- [ ] Update the `11ty.compatibility` field in package.json

**Eleventy 2.0.0 milestone**
https://github.com/11ty/eleventy/milestone/38
